config/routes.rb
 Rails.application.routes.draw do
  
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#set root to home page
root to: "pages#home"

#excludes show so that a custom route can be added for it
resources :dev_portfolios, except: [:show, :index] do
    put :sort, on: :collection
end
  get "portfolios", to: 'dev_portfolios#index'
  get "portfolios/new", to: 'dev_portfolios#new'
  #use as to generate a custom prefix as this route will not have a prefix by itself
  get 'portfolios/:id', to: 'dev_portfolios#show', as: "portfolio_show"
  get 'react_items', to: 'dev_portfolios#react'
resources :blogs do
	member do
		get :toggle_status 
	end
end

#this replaces get 'pages/about' which assumes that pages is the controller and contact is the action
  get 'about', to: 'pages#about'
#maps the route to controller on left of hash and action on right
  get 'contact', to: 'pages#contact'
# because it's mapped you can pass w/e you want in the url e.g. get 'asdfasd'


  # get 'tech_news', to: 'pages#tech_news'
 


end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: { draft: 0, published: 1 }
	extend FriendlyId
	# This takes the title of the blogpost and creates a slug for the url
	friendly_id :title, use: :slugged

# requires any post to have a title and body before it will create
	validates_presence_of :title, :body, :topic_id
	belongs_to :topic, optional: true


	def self.recent
		order("created_at DESC")
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_sidebar_topics, except: [:create, :update, :destroy, :toggle_status]
  layout "blog"
  #access all= everyone can look at index and show regardless of their status
  #User except= general users cannot access the destroy method, commentors can't delete or create blogs
  #site_admin= the administrator has access to everything
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all
  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(5)
    else
      @blogs = Blog.published.recent.page(params[:page]).per(5)
    end
    @page_title="My Portfolio | Blog"
    @tweets=SocialTool.twitter_search

  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
       if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.friendly.find(params[:id])
    else
      redirect_to blogs_path, notice: "You're not meant to see that"
    end
    @page_title=@blog.title
    @tweets=SocialTool.twitter_search
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @tweets=SocialTool.twitter_search
  end

  # GET /blogs/1/edit
  def edit
    @tweets=SocialTool.twitter_search
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @tweets=SocialTool.twitter_search

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    @tweets=SocialTool.twitter_search
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @tweets=SocialTool.twitter_search
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
def toggle_status
    if @blog.draft?
      @blog.published!
     elsif @blog.published?
      @blog.draft!
    end
  redirect_to blogs_url, notice: "Post status updated"
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      # overrides the default behavior
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

  def set_sidebar_topics
        @side_bar_topics= Topic.with_blogs

  end

end

app/helpers/blogs_helper.rb
module BlogsHelper

	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			CodeRay.scan(code, language).div
		end
	end

	def markdown(text)
		coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)
		options ={
			fenced_code_blocks: true,
			no_intra_emphasis: true,
			autolink: true,
			lax_html_blocks: true,
		}

		markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
		markdown_to_html.render(text).html_safe
	end

	def blog_status_color(blog)
		"color: red;" if blog.draft?
		
	end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
	<nav class="breadcrumb blogcrumb"> 
    <%= link_to fa_icon('floppy-o'),toggle_status_blog_path(blog), style: blog_status_color(blog) %>
    <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog)%>

    <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %>
	</nav>
<% end %>

app/views/blogs/_blog.html.erb
    
<div class="blog-post">
      <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
      <p class="blog-post-meta"> Posted: <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

      <%= render partial: 'blogs/admin_actions', locals: {blog: blog} %>

      <p>  <%= blog.body %> </p>
</div>
   

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
      <% end %>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, id: :blog_title, class: 'form-control', placeholder: "Title"%>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title,
                                {
                                  selected: blog.topic_id,
                                  include_blank: true
                                  },
                                  class: 'form-control') %>
  </div>

<div class="form-group">
  <%=form.radio_button :status, 'draft' %>
  <%=form.label :status, 'Draft' %>
  <%=form.radio_button :status, 'published' %>
  <%=form.label :status, 'Published' %>
</div>
  <div class="form-group">
    <%= form.text_area :body, id: :blog_body, class: 'form-control', rows:10, placeholder: "Body" %>
  </div>

  <div class="actions">
    <%= form.submit "Post", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
	

<h1>Editing Blog</h1>
<%= link_to 'Show', @blog %> 

<%= render 'form', blog: @blog %>
<br />
<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<!-- if the pagination class is up when there are no pages it throws off the column for some reason, set to only display when there is more than one page worth of blog content -->
<% if Blog.published.count > 5 %>
 <div class="paginate">
    <%=paginate @blogs %>
  </div>
<% end %>
<div class="col-sm-8 blog-main">
 <br />
    <%= render @blogs%>
<div class="paginate">
    <%=paginate @blogs %>
  </div>
</div><!-- /.blog-post -->

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>
<br />
<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

<nav class="breadcrumb row">
	<div class="col">
<%= link_to "Blogs", blogs_path, class: 'breadcrumb-item' %>
<%= link_to @blog.topic.title, topic_path(@blog.topic), class: 'breadcrumb-item' %>
  <span class="breadcrumb-item active"><%= @blog.title%></span>

  <span class="float-right">
  
  	<%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) if logged_in?(:site_admin) %>
  	<%= link_to fa_icon('trash'), @blog, method: :delete, data:{confirm: 'Are you sure?'} if logged_in?(:site_admin) %>
  </span>
</div>
</nav>

<h2>  <%= @blog.title %> </h2>


<p>
	  <%= markdown(@blog.body) %>

</p>
<%= link_to 'Back', blogs_path %>

</div><!-- /.blog-post -->