config/routes.rb
 Rails.application.routes.draw do
  
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#set root to home page
root to: "pages#home"

#excludes show so that a custom route can be added for it
resources :dev_portfolios, except: [:show, :index] do
    put :sort, on: :collection
end
  get "portfolios", to: 'dev_portfolios#index'
  get "portfolios/new", to: 'dev_portfolios#new'
  #use as to generate a custom prefix as this route will not have a prefix by itself
  get 'portfolios/:id', to: 'dev_portfolios#show', as: "portfolio_show"
  get 'react_items', to: 'dev_portfolios#react'
resources :blogs do
	member do
		get :toggle_status 
	end
end

#this replaces get 'pages/about' which assumes that pages is the controller and contact is the action
  get 'about', to: 'pages#about'
#maps the route to controller on left of hash and action on right
  get 'contact', to: 'pages#contact'
# because it's mapped you can pass w/e you want in the url e.g. get 'asdfasd'


  # get 'tech_news', to: 'pages#tech_news'
 


end

app/views/shared/_alerts.html.erb
<!-- #Depreciated -->

<% if flash[:alert] %>
	<%= js add_gritter(flash[:alert], title: "Paul's Portfolio", sticky: false) %>
<% elsif flash[:error] %>
	<%=js add_gritter(flash[:error], title: "Paul's Portfolio", sticky: false) %>
<% else %>
	<%= js add_gritter(flash[:notice], title: "Paul's Portfolio", sticky: false) %> 
<%end%>

app/views/shared/_application_footer.html.erb
<footer class="mastfoot">
   <div class="inner">
      <%= @copyright %>
   </div>
</footer>

app/views/shared/_application_nav.html.erb
 <header class="masthead clearfix">
 	<div class="inner">
 		<div class="brand-link">
	   	<h3 class="masthead-brand">Paul Aguilar</h3>
	   </div>
	    <nav class="nav nav-masthead nav_styles">

	    	<%= nav_helper "nav-link", "span"%>
	    	<%= login_helper("nav-link")%>

        </nav>
     </div>
 </header> 




<!-- old code left as an example -->
 <!-- 	    	<%= link_to "Home", root_path, class: 'nav-link' %>
	    	<%= link_to "About", about_path, class: 'nav-link'%>
	    	<%= link_to "Contact", contact_path, class: 'nav-link'%>
	    	<%= link_to "Blog", blogs_path, class: 'nav-link'%>
	    	<%= link_to "Portfolio", portfolios_path, class: 'nav-link'%> -->

app/views/shared/_blog_footer.html.erb
 <footer class="blog-footer">
 	        <a href="#">Back to top</a>

      <p>
      	<%= @copyright %>
      </p>
      
    </footer>

app/views/shared/_blog_header.html.erb
<header>
      <div class="blog-header">
        <div class="container">
          <h1 class="blog-title">The Dev Log</h1>
          <p class="lead blog-description">Thinking, Collecting, and <em>sometimes</em> Writing</p>
          <% if logged_in?(:site_admin)%>
          <span class="btn btn-light">
            <%= link_to 'Create a New Post', new_blog_path %>
          </span>
          <span class="btn btn-light">
			      <%= link_to "Topics", topics_path %>
		      </span>
          <% end %>
        </div>


      </div>
    </header>

app/views/shared/_blog_nav.html.erb
      <div class="blog-masthead">
          <nav class="navbar navbar-expand-lg navbar-dark">
  
           <h4 class="name navbar-brand"> Paul Aguilar</h4>
             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
             <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

          <%= nav_helper "nav-link", "span"%>
          <%= login_helper "nav-link" %>

            </div>
          </nav>
        </div>
      </div>


     <!--    <%= link_to "Home", root_path, class: "nav-link "%>
        <%= link_to "About", about_path, class: "nav-link "%>
        <%= link_to "Contact", contact_path, class: "nav-link "%>
        <%= link_to "Blog", blogs_path, class: "nav-link"%>
        <%= link_to "Portfolio", portfolios_path, class: "nav-link"%>
 -->

app/views/shared/_blog_sidebar.html.erb
<aside class="col-sm-3 ml-sm-auto blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Bienvenue, here's a blog that I made for myself as a dev journal to update status on projects, things I've learned, or notes in general.</p>
          </div>
<!--      <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div> -->

          <div class="sidebar-module">
            <h4> Topics</h4>
            <% @side_bar_topics.each do |topic| %>
              <p><%=link_to topic.title, topic_path(topic) %></p>
            <% end %>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled social-links">
              <li><a href="https://gitlab.com/clearfix99"><%=fa_icon "gitlab"%></a></li>
              <li><a href="https://www.linkedin.com/in/paul-aguilar-12134296"><%=fa_icon "linkedin"%></a></li>
              <li><a href="https://twitter.com"><%=fa_icon "twitter"%></a></li>
              
            </ol>
          </div>
          <br />
          <div class="sidebar-module">
          <h4 class="tech-header"> Rails News </h4>
          <% @tweets.each do |tweet| %>
          <div class="tech-news">
            <div class="card sidebar-module-inset">
              <%=twitter_parser tweet %>
            </div>
          </div>
          <% end %>
        </div>
        </aside><!-- /.blog-sidebar -->

app/views/shared/_dev_portfolio_footer.html.erb
<footer class="text-muted footer">
      <div class="container">
        <p class="float-left">
          <a href="#">Back to top</a>
        </p>

       <p class="float-right"><%= @copyright %></p>
      </div>
    </footer>

app/views/shared/_dev_portfolio_jumbo.html.erb
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">My Portfolio</h1>
          <p class="lead text-muted">Here are some of the things that I've worked on since I started learning web development. Some of the languages and frameworks I've worked with include:</p>
          <div class="logos" >
          <%= image_tag "html5.png", width: 50, alt: "HTML5" %>
          <%= image_tag "css3.png", width: 50, alt: "CSS3" %>
          <%= image_tag "bootstrap.png", width: 50, alt: "Bootstrap" %>
          <%= image_tag "ruby.png", width: 55, alt: "Ruby" %>
          <%= image_tag "rails.png", width: 55, alt: "Rails" %>
          <%= image_tag "postgresql.svg", width: 50, alt: "Postgresql" %>
          <%= image_tag "git.png", width: 50, alt: "Git" %>
        </div>
          <br />
          <p>
            <%= link_to "Learn More", about_path, class:"btn btn-primary"%>
            <%= link_to "Contact Me", contact_path, class:"btn btn-secondary" %>
          </p>
        </div>
      </section> 

      

app/views/shared/_dev_portfolio_nav.html.erb
	<header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 py-4">
            <h4 class="text-white">About</h4>
            <p class="text-muted">Welcome to my portfolio, here are a few of the things I've worked on as of now. HTML5 and CSS3 were the first languages I looked at when I started learning web design and to my surprise I just kept finding more. My javascript is still rough so no projects have used that up to now but I would like to incorporate it soon. </p>
            
          </div>
          <div class="col-sm-4 py-4">
            <h4 class="text-white">Explore</h4>
            <ul class="list-unstyled">
              <%= nav_helper "text-white", "li"%>
              <li> <%= login_helper "text-white" %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>


      <div class="navbar navbar-dark bg-dark">
      <div class="container d-flex justify-content-between">
        <h2 class="navbar-brand">  Paul Aguilar</h2>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>

app/views/shared/_nav.html.erb
 <div class="<%= location %>">
      <div><%= link_to "Home", root_path%></div>
      <div><%= link_to "About", about_path%></div>
      <div><%= link_to "Contact", contact_path%></div>
      <div><%= link_to "Blog", blogs_path%></div>
      <div><%= link_to "Portfolio", portfolios_path%></div>
 </div>