config/routes.rb
 Rails.application.routes.draw do
  
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#set root to home page
root to: "pages#home"

#excludes show so that a custom route can be added for it
resources :dev_portfolios, except: [:show, :index] do
    put :sort, on: :collection
end
  get "portfolios", to: 'dev_portfolios#index'
  get "portfolios/new", to: 'dev_portfolios#new'
  #use as to generate a custom prefix as this route will not have a prefix by itself
  get 'portfolios/:id', to: 'dev_portfolios#show', as: "portfolio_show"
  get 'react_items', to: 'dev_portfolios#react'
resources :blogs do
	member do
		get :toggle_status 
	end
end

#this replaces get 'pages/about' which assumes that pages is the controller and contact is the action
  get 'about', to: 'pages#about'
#maps the route to controller on left of hash and action on right
  get 'contact', to: 'pages#contact'
# because it's mapped you can pass w/e you want in the url e.g. get 'asdfasd'


  # get 'tech_news', to: 'pages#tech_news'
 


end

app/models/dev_portfolio.rb
class DevPortfolio < ApplicationRecord
	has_many :technologies
	accepts_nested_attributes_for :technologies, 
								   allow_destroy: true,
									reject_if: lambda {|attr| attr['name'].blank?}


	# include Placeholder
	validates_presence_of :title, :body

	mount_uploader :thumbnail, DevPortfolioUploader
	mount_uploader :main_image, DevPortfolioUploader



# using these methods is considered best practice as it forces you to keep all the logic for the model in the model file
	def self.react
		where(subtitle: 'React')
		
	end

	def self.by_position
		order("position ASC")
	end



# creating a custom scope using a lambda
	scope :ruby_on_rails, ->{where(subtitle: 'Ruby on Rails')}

#after a portfolio item is started a default image and thumbnail is added
	# after_initialize :set_defaults
	# def set_defaults
	# 	self.main_image ||=Placeholder.image_generator(height: '600', width: '400')
	# 	self.thumbnail ||=Placeholder.image_generator(height: '350', width: '200')
	# end



end

app/controllers/dev_portfolios_controller.rb
class DevPortfoliosController < ApplicationController
  layout "portfolio"
  access all: [:show, :index, :react], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    # accessed from the react method in dev_portfolio.rb
  @portfolio=DevPortfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      DevPortfolio.find(value[:id]).update(position: value[:position])
    end
    render body: nil
  end

  def react
    @react_portfolio=DevPortfolio.react
  end
#making @portfolio available to view
  def new
    @portfolio=DevPortfolio.new
  end

#need to make it available and connect to db
  def create
    #params that are allowed
    @portfolio=DevPortfolio.new(dev_portfolio_params)
    
    respond_to do|format|
      if @portfolio.save
        format.html {redirect_to portfolios_path, notice: "Your portfolio item is now live"}
      else
        format.html{render :new}
      end
    end
  end

  def edit
    #pass in the id from article to direct rails to what you want edited
    @portfolio=DevPortfolio.find(params[:id])
  end

  def update
    @portfolio=DevPortfolio.find(params[:id])

    respond_to do |f|
      if @portfolio.update(dev_portfolio_params)
        f.html { redirect_to portfolios_path, notice: "Your portfolio item has been updated"}
      else
        f.html {render :edit}
      end
    end
  end
def show
  @portfolio=DevPortfolio.find(params[:id])
end

def destroy
  #perform look up
  @portfolio=DevPortfolio.find(params[:id])
  # destroy the record
  @portfolio.destroy
  #redirect
  respond_to do |f|
    f.html {redirect_to portfolios_url, notice: "This item has been deleted"}
    end
  end

private
#refactor strongg params for ease of access
  def dev_portfolio_params
    params.require(:dev_portfolio).permit(:title, 
                                          :subtitle,
                                          :body,
                                          :main_image,
                                          :thumbnail,
                                          technologies_attributes: [:id, :name, :_destroy]
                                          )
  end


end

app/helpers/dev_portfolios_helper.rb
module DevPortfoliosHelper

	def image_generator(height:, width:)
		"https://via.placeholder.com/#{height}x#{width} " 
	end
	
end

# self.main_image ||=Placeholder.image_generator(height: '600', width: '400')
# 	self.thumbnail ||=Placeholder.image_generator(height: '350', width: '200')
def placeholder_img img, type
	if img.model.main_image? || img.model.thumbnail?		
		img
	elsif type=='thumb'
		image_generator(height:'356', width:'250')
	elsif type =='main'
		image_generator(height:'600', width: '400')
	end 
		
	
end

app/views/dev_portfolios/_form.html.erb
<%= form_for(@portfolio) do |form| %>
  <% if @portfolio.errors.any? %>
    <% @portfolio.errors.full_messages.each do |error| %>
      <%= alert_generator error%>
      <% end %>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title,  class:"form-control" %>
  </div>
   <div class="form-group">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle,  class:"form-control" %>
  </div>

 <div class="form-group">
  <label class="btn btn-primary">
    Upload Thumbnail
    <%=form.file_field :thumbnail, style: 'display:none;'  %>
  </label>
  </div>


  <div class="form-group">
    <label class="btn btn-primary">
    Upload Main Image
    <%=form.file_field :main_image, style: 'display:none;' %>
  </label>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body,  class:"form-control", rows:5 %>
  </div>
    <hr>
    <div>
      <h3>Technologies Used </h3>
        <!--       gives the ability to create nested form -->      
        <%= form.fields_for :technologies do |tech|%>
             <%= render 'technology_fields', f: tech %> 
        <% end %>
        <div>
          <%= link_to_add_association "Add Technology", form, :technologies %>
        </div>
    </div>
    <br />
  <div class="actions form-group">
    <%= form.submit "Save Portfolio Item", class:"btn btn-primary" %>
  </div>
<% end %>
<p><%= link_to "Back", portfolios_path %></p>

app/views/dev_portfolios/_portfolio.html.erb
<div class="col-md-4">
  <!--  Made the title my view --> 
  <div class="card" data-id="<%=portfolio.id%>">
<%=image_tag placeholder_img(portfolio.thumbnail, 'thumb'), width: "100%" %><br />
    <p class="card-text">
      <span><%=link_to portfolio.title, portfolio_show_path(portfolio.id)%><span>
      <%=portfolio.subtitle%>
      <span class="links">
      <%= link_to "Edit", edit_dev_portfolio_path(portfolio) if logged_in?(:site_admin)%>
<%= link_to "Delete",dev_portfolio_path(portfolio), method: :delete, data: {confirm: 'Are you sure?'} if logged_in?(:site_admin)%>
</span>
  </p>
  </div>
</div>

app/views/dev_portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
	<%= f.label :name %>
	<%= f.text_field :name, class:"form-control" %>
	<%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/dev_portfolios/edit.html.erb
<div class="container portfolio_edit">
  <h1>Edit Portfolio Item</h1>
<!-- 

<%= form_for(@portfolio) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<p><%= link_to "Back", portfolios_path %></p> -->

<%= render "form", portfolio: @portfolio %>
</div>

app/views/dev_portfolios/index.html.erb
      <div class="album text-muted">
        <div class="container">
				<%= link_to "Add Entry", new_dev_portfolio_path if logged_in?(:site_admin)%>

          <div class="row <%= 'sortable' if logged_in?(:site_admin)%>">
				<!-- manual way: <a href="dev_portfolios/new">Create New Item</a> -->
				<!-- use "path" to get the relative url  -->
				<%= render partial: 'portfolio', collection: @portfolio%>
          </div>
      </div>
  </div>

app/views/dev_portfolios/new.html.erb
<div class="container portfolio_edit">
<h1>Create a new Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/dev_portfolios/react.html.erb
<h1>Portfolio</h1>
<!-- manual way: <a href="dev_portfolios/new">Create New Item</a> -->
<!-- use "path" to get the relative url  -->
<%= link_to "Create New Item", new_dev_portfolio_path %>
<%@react_portfolio.each do|x|%>
  <p><%=x.title%></P>
  <p><%=x.subtitle%></P>
  <p><%=x.body%></P>
  <%=image_tag x.thumbnail unless x.thumbnail.nil?%><br />
  <%=link_to "View", portfolio_show_path(x.id)%>
  <%= link_to "Edit", edit_dev_portfolio_path(x) if logged_in?(:site_admin)%>
  <%= link_to "Delete",dev_portfolio_path(x), method: :delete, data: {confirm: 'Are you sure?'} if logged_in?(:site_admin)%>
<%end%>

app/views/dev_portfolios/show.html.erb
<div class="container">
	<div class="row main_container">
		<div class="col-md-7">
			<%= image_tag placeholder_img(@portfolio.main_image, 'main'), width: "100%" %>
			<br />
					<p><%= link_to "Back", portfolios_path %></p>

		</div>
		<div class="col-md-5">
			<h1><%= @portfolio.title %></h1>
			<h3><%= @portfolio.subtitle %></h3>
			<p><%= @portfolio.body%>
			<h6>Technologies Used:</h6>
			<% @portfolio.technologies.each do |t| %>
			<p>
				<%=t.name%>
			</p>
			<%end%>
              	<%= link_to "Edit Item", edit_dev_portfolio_path(@portfolio), class:"btn btn-warning btn-color" if logged_in?(:site_admin)%>
		</div>
		<div class="col-md-12"><hr></div>
	</div>
</div>